name: picoproj
description: A new Flutter project
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  at_client_mobile:
  at_utils:
  path_provider: 
  flutter_dotenv:
  at_app_flutter:
  at_onboarding_flutter: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - .env

